export const SHOW_MODAL_REQUEST = "SHOW_MODAL_REQUEST"
export const SHOW_MODAL_SUCCESS = "SHOW_MODAL_SUCCESS"
export const SHOW_MODAL_FAILURE = "SHOW_MODAL_FAILURE"

export const CLOSE_MODAL = "CLOSE_MODAL"