export const LOAD_ALL_POST_REQUEST = "LOAD_ALL_POST_REQUEST";
export const LOAD_ALL_POST_SUCCESS = "LOAD_ALL_POST_SUCCESS";
export const LOAD_ALL_POST_FAILURE = "LOAD_ALL_POST_FAILURE";

export const LOAD_POST_WITH_REQUEST = "LOAD_POST_WITH_REQUEST";
export const LOAD_POST_WITH_SUCCESS = "LOAD_POST_WITH_SUCCESS";
export const LOAD_POST_WITH_FAILURE = "LOAD__POST_WITH_FAILURE";

export const UPLOAD_POST_REQUEST = "UPLOAD_POST_REQUEST";
export const UPLOAD_POST_SUCCESS = "UPLOAD_POST_SUCCESS";
export const UPLOAD_POST_FAILURE = "UPLOAD_POST_FAILURE";

export const UPLOAD_CLAN_POST_REQUEST = "UPLOAD_CLAN_POST_REQUEST";
export const UPLOAD_CLAN_POST_SUCCESS = "UPLOAD_CLAN_POST_SUCCESS";
export const UPLOAD_CLAN_POST_FAILURE = "UPLOAD_CLAN_POST_FAILURE";

export const LIKED_POST_REQUEST = "LIKED_POST_REQUEST";
export const LIKED_POST_SUCCESS = "LIKED_POST_SUCCESS";
export const LIKED_POST_FAILURE = "LIKED_POST_FAILURE";

export const UNLIKED_POST_REQUEST = "UNLIKED_POST_REQUEST";
export const UNLIKED_POST_SUCCESS = "UNLIKED_POST_SUCCESS";
export const UNLIKED_POST_FAILURE = "UNLIKED_POST_FAILURE";

export const ADD_COMMENT_REQUEST = "ADD_COMMENT_REQUEST";
export const ADD_COMMENT_SUCCESS = "ADD_COMMENT_SUCCESS";
export const ADD_COMMENT_FAILURE = "ADD_COMMENT_FAILURE";

export const PICK_COMMENT_TO_REPLY = "PICK_COMMENT_TO_REPLY"

export const ADD_REPLY_REQUEST = "ADD_REPLY_REQUEST";
export const ADD_REPLY_SUCCESS = "ADD_REPLY_SUCCESS";
export const ADD_REPLY_FAILURE = "ADD_REPLY_FAILURE";

export const LOAD_FULL_POST_REQUEST = "LOAD_FULL_POST_REQUEST"
export const LOAD_FULL_POST_SUCCESS = "LOAD_FULL_POST_SUCCESS"
export const LOAD_FULL_POST_FAILURE = "LOAD_FULL_POST_FAILURE"

export const LOAD_TOP20_LIKED_POST_REQUEST = "LOAD_TOP20_LIKED_POST_REQUEST"
export const LOAD_TOP20_LIKED_POST_SUCCESS = "LOAD_TOP20_LIKED_POST_SUCCESS"
export const LOAD_TOP20_LIKED_POST_FAILURE = "LOAD_TOP20_LIKED_POST_FAILURE"

export const DELETE_POST_REQUEST = "DELETE_POST_REQUEST"
export const DELETE_POST_SUCCESS = "DELETE_POST_SUCCESS"
export const DELETE_POST_FAILURE = "DELETE_POST_FAILURE"

export const LIKE_COMMENT_REQUEST = "LIKE_COMMENT_REQUEST"
export const LIKE_COMMENT_SUCCESS = "LIKE_COMMENT_SUCCESS"
export const LIKE_COMMENT_FAILURE = "LIKE_COMMENT_FAILURE"

export const UNLIKE_COMMENT_REQUEST = "UNLIKE_COMMENT_REQUEST"
export const UNLIKE_COMMENT_SUCCESS = "UNLIKE_COMMENT_SUCCESS"
export const UNLIKE_COMMENT_FAILURE = "UNLIKE_COMMENT_FAILURE"

export const SORT_POSTS = "SORT_POSTS"