export const SIGNUP_REQUEST = "SIGNUP_REQUEST";
export const SIGNUP_SUCCESS = "SIGNUP_SUCCESS";
export const SIGNUP_FAILURE = "SIGNUP_FAILURE";

export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';

export const LOGOUT_REQUEST = 'LOGOUT_REQUEST';
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';
export const LOGOUT_FAILURE = 'LOGOUT_FAILURE';

export const GET_LOGIN_PLATFORM_REQUEST = 'GET_LOGIN_PLATFORM_REQUEST';

export const LOAD_USER_REQUEST = "LOAD_USER_REQUEST";
export const LOAD_USER_SUCCESS = "LOAD_USER_SUCCESS";
export const LOAD_USER_FAILURE = "LOAD_USER_FAILURE";

export const LOAD_MY_PROFILE_REQUEST = "LOAD_MY_PROFILE_REQUEST";
export const LOAD_MY_PROFILE_SUCCESS = "LOAD_MY_PROFILE_SUCCESS";
export const LOAD_MY_PROFILE_FAILURE = "LOAD_MY_PROFILE_FAILURE";

export const AUTH_WITH_EMAIL_REQUEST = "AUTH_WITH_EMAIL_REQUEST";
export const AUTH_WITH_EMAIL_SUCCESS = "AUTH_WITH_EMAIL_SUCCESS";
export const AUTH_WITH_EMAIL_FAILURE = "AUTH_WITH_EMAIL_FAILURE";

export const CREATE_CLAN_REQUEST = "CREATE_CLAN_REQUEST";
export const CREATE_CLAN_SUCCESS = "CREATE_CLAN_SUCCESS";
export const CREATE_CLAN_FAILURE = "CREATE_CLAN_FAILURE";

export const GET_CLAN_DATA_REQUEST = "GET_CLAN_DATA_REQUEST";
export const GET_CLAN_DATA_SUCCESS = "GET_CLAN_DATA_SUCCESS";
export const GET_CLAN_DATA_FAILURE = "GET_CLAN_DATA_FAILURE";

export const GET_RECOMMEND_ACCOUNT_REQUEST = "GET_RECOMMEND_ACCOUNT_REQUEST";
export const GET_RECOMMEND_ACCOUNT_SUCCESS = "GET_RECOMMEND_ACCOUNT_SUCCESS";
export const GET_RECOMMEND_ACCOUNT_FAILURE = "GET_RECOMMEND_ACCOUNT_FAILURE";

export const FOLLOW_ACCOUNT_REQUEST = "FOLLOW_ACCOUNT_REQUEST";
export const FOLLOW_ACCOUNT_SUCCESS = "FOLLOW_ACCOUNT_SUCCESS";
export const FOLLOW_ACCOUNT_FAILURE = "FOLLOW_ACCOUNT_FAILURE";

export const UNFOLLOW_ACCOUNT_REQUEST = "UNFOLLOW_ACCOUNT_REQUEST";
export const UNFOLLOW_ACCOUNT_SUCCESS = "UNFOLLOW_ACCOUNT_SUCCESS";
export const UNFOLLOW_ACCOUNT_FAILURE = "UNFOLLOW_ACCOUNT_FAILURE";

export const SUBSCRIBE_CLAN_REQUEST = "SUBSCRIBE_CLAN_REQUEST";
export const SUBSCRIBE_CLAN_SUCCESS = "SUBSCRIBE_CLAN_SUCCESS";
export const SUBSCRIBE_CLAN_FAILURE = "SUBSCRIBE_CLAN_FAILURE";

export const UNSUBSCRIBE_CLAN_REQUEST = "UNSUBSCRIBE_CLAN_REQUEST";
export const UNSUBSCRIBE_CLAN_SUCCESS = "UNSUBSCRIBE_CLAN_SUCCESS";
export const UNSUBSCRIBE_CLAN_FAILURE = "UNSUBSCRIBE_CLAN_FAILURE";

export const CREATE_FAVORITE_LIST_REQUEST = "CREATE_FAVORITE_LIST_REQUEST"
export const CREATE_FAVORITE_LIST_SUCCESS = "CREATE_FAVORITE_LIST_SUCCESS"
export const CREATE_FAVORITE_LIST_FAILURE = "CREATE_FAVORITE_LIST_FAILURE"

export const ADD_TO_FAVORITE_LIST_REQUEST = "ADD_TO_FAVORITE_LIST_REQUEST"
export const ADD_TO_FAVORITE_LIST_SUCCESS = "ADD_TO_FAVORITE_LIST_SUCCESS"
export const ADD_TO_FAVORITE_LIST_FAILURE = "ADD_TO_FAVORITE_LIST_FAILURE"

export const REMOVE_TO_FAVORITE_LIST_REQUEST = "REMOVE_TO_FAVORITE_LIST_REQUEST"
export const REMOVE_TO_FAVORITE_LIST_SUCCESS = "REMOVE_TO_FAVORITE_LIST_SUCCESS"
export const REMOVE_TO_FAVORITE_LIST_FAILURE = "REMOVE_TO_FAVORITE_LIST_FAILURE"

export const CHECK_USERNAME_REQUEST = "CHECK_USERNAME_REQUEST"
export const CHECK_USERNAME_SUCCESS = "CHECK_USERNAME_SUCCESS"
export const CHECK_USERNAME_FAILURE = "CHECK_USERNAME_FAILURE"

export const REMOVE_ALBUM_REQUEST = "REMOVE_ALBUM_REQUEST"
export const REMOVE_ALBUM_SUCCESS = "REMOVE_ALBUM_SUCCESS"
export const REMOVE_ALBUM_FAILURE = "REMOVE_ALBUM_FAILURE"

export const UPDATE_ALBUM_REQUEST = "UPDATE_ALBUM_REQUEST"
export const UPDATE_ALBUM_SUCCESS = "UPDATE_ALBUM_SUCCESS"
export const UPDATE_ALBUM_FAILURE = "UPDATE_ALBUM_FAILURE"

export const UPDATE_PROFILE_REQUEST = "UPDATE_PROFILE_REQUEST"
export const UPDATE_PROFILE_SUCCESS = "UPDATE_PROFILE_SUCCESS"
export const UPDATE_PROFILE_FAILURE = "UPDATE_PROFILE_FAILURE"

export const UPDATE_CLAN_REQUEST = "UPDATE_CLAN_REQUEST"
export const UPDATE_CLAN_SUCCESS = "UPDATE_CLAN_SUCCESS"
export const UPDATE_CLAN_FAILURE = "UPDATE_CLAN_FAILURE"

export const DELETE_CLAN_REQUEST = "DELETE_CLAN_REQUEST"
export const DELETE_CLAN_SUCCESS = "DELETE_CLAN_SUCCESS"
export const DELETE_CLAN_FAILURE = "DELETE_CLAN_FAILURE"

export const BOOKMARK_POST_REQUEST = "BOOKMARK_POST_REQUEST"
export const BOOKMARK_POST_SUCCESS = "BOOKMARK_POST_SUCCESS"
export const BOOKMARK_POST_FAILURE = "BOOKMARK_POST_FAILURE"

export const UNBOOKMARK_POST_REQUEST = "UNBOOKMARK_POST_REQUEST"
export const UNBOOKMARK_POST_SUCCESS = "UNBOOKMARK_POST_SUCCESS"
export const UNBOOKMARK_POST_FAILURE = "UNBOOKMARK_POST_FAILURE"