export const LOGIN_REQUEST = 'LOGIN_REQUEST'
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS'
export const LOGIN_FAILURE = 'LOGIN_FAILURE'

export const GET_LOGIN_PLATFORM_REQUEST = 'GET_LOGIN_PLATFORM_REQUEST'

export const GOOGLE_LOGIN_REQUEST = "GOOGLE_LOGIN_REQUEST"
export const LOCAL_LOGIN_REQUEST = "LOCAL_LOGIN_REQUEST"

export const GOOGLE_LOAD_USER_REQUEST = "GOOGLE_LOAD_USER_REQUEST"
export const GOOGLE_LOAD_USER_SUCCESS = "GOOGLE_LOAD_USER_SUCCESS"
export const GOOGLE_LOAD_USER_FAILURE = "GOOGLE_LOAD_USER_FAILURE"

export const LOCAL_LOAD_USER_REQUEST = "LOCAL_LOAD_USER_REQUEST"
export const LOCAL_LOAD_USER_SUCCESS = "LOCAL_LOAD_USER_SUCCESS"
export const LOCAL_LOAD_USER_FAILURE = "LOCAL_LOAD_USER_FAILURE"

export const SIGNUP_REQUEST = "SIGNUP_REQUEST"
export const SIGNUP_SUCCESS = "SIGNUP_SUCCESS"
export const SIGNUP_FAILURE = "SIGNUP_FAILURE"